services:
  api:
    image: project/mlops_project/api:0.0
    container_name: reco_api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      - LOG__LEVEL=debug
    networks:
      reco_network:
        ipv4_address: 172.19.0.5
    ports:
      - "8000:8000"

  test_api:
    image: python:3.10
    depends_on:
      - api
    environment:
      - IPV4_API=172.19.0.5
    networks:
      - reco_network
    ports:
      - "8000:8000"

  dev:
    image: project/mlops_project/dev:0.0
    container_name: reco_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - LOG__LEVEL=debug
    volumes:
      - ./pyproject.toml:/opt/workspace/pyproject.toml
      - ./models:/opt/workspace/models
      - ./data:/opt/workspace/data
      - ./src:/opt/workspace/src
      - ./tests:/opt/workspace/tests
      - ./app.py:/opt/workspace/app.py
      - ./api.py:/opt/workspace/api.py
    network_mode: host
    ports:
      - "8000:8000"
    command: bash

  mlflow-server:
    image: mlflow/mlflow:latest
    container_name: mlflow_server
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlflow:/mlflow
    networks:
      reco_network:
        ipv4_address: 172.19.0.6
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      reco_network:
        ipv4_address: 172.19.0.7
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      reco_network:
        ipv4_address: 172.19.0.8
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  reco_network:
    name: reco_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
