version: '3.8'

services:
  api:
    image: project/mlops_project/api:0.0
    container_name: reco_api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      - LOG__LEVEL=debug
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    networks:
      reco_network:
        ipv4_address: 192.168.100.5
    ports:
      - "8000:8000"

  test_api:
    image: python:3.10
    depends_on:
      - api
    environment:
      - IPV4_API=192.168.100.5
    networks:
      reco_network:
        ipv4_address: 192.168.100.10
    ports:
      - "8001:8000"

  dev:
    image: project/mlops_project/dev:0.0
    container_name: reco_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - LOG__LEVEL=debug
    volumes:
      - ./pyproject.toml:/opt/workspace/pyproject.toml
      - ./models:/opt/workspace/models
      - ./data:/opt/workspace/data
      - ./src:/opt/workspace/src
      - ./tests:/opt/workspace/tests
      - ./app.py:/opt/workspace/app.py
      - ./api.py:/opt/workspace/api.py
    networks:
      reco_network:
        ipv4_address: 192.168.100.9
    ports:
      - "8002:8000"
    command: uvicorn api:api --host 0.0.0.0 --port 8000 --reload

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.17.2
    container_name: mlflow_server
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlflow:/mlflow
      - ./mlruns:/mlruns
    networks:
      reco_network:
        ipv4_address: 192.168.100.6
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000

  csv_exporter:
    build:
      context: .
      dockerfile: Dockerfile
      target: csv_exporter  
    container_name: csv_exporter
    volumes:
      - ./predictions/predictions_log.csv:/data/predictions_log.csv:ro
    networks:
      reco_network:
        ipv4_address: 192.168.100.12
    ports:
      - "9101:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      reco_network:
        ipv4_address: 192.168.100.7
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
    networks:
      reco_network:
        ipv4_address: 192.168.100.8
    ports:
      - "3001:3000"


volumes:
  grafana-storage:

networks:
  reco_network:
    name: reco_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
