name: Unittest

on: [push]
jobs:
  test:
    runs-on: python:3.10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run unittest
        run: poetry run pytest -s tests/test_dummy.py